// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLOL-G3xIHVebCg9OU4RattHrvTvIT0U',
    appId: '1:37191378668:android:38060407d195a9941f27c9',
    messagingSenderId: '37191378668',
    projectId: 'denter-a6ed9',
    databaseURL: 'https://denter-a6ed9-default-rtdb.firebaseio.com',
    storageBucket: 'denter-a6ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhDXcoNVXL1aQsb_FArQvbKbNYV1-ywsI',
    appId: '1:37191378668:ios:029dab1ab165123f1f27c9',
    messagingSenderId: '37191378668',
    projectId: 'denter-a6ed9',
    databaseURL: 'https://denter-a6ed9-default-rtdb.firebaseio.com',
    storageBucket: 'denter-a6ed9.appspot.com',
    iosClientId: '37191378668-sf7rf811n7vhkobcm59n7ur1mopu71gq.apps.googleusercontent.com',
    iosBundleId: 'br.com.powerance.denterpatient.code',
  );
}
